name: GitHub-Discord Bridge

on:
  push:
  pull_request:
  issues:
  release:
    types: [published]

jobs:
  bridge:
    runs-on: ubuntu-latest
    environment: prod  # Add this line!

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Bridge
        uses: gkr0110/github-discord-bridge@main
        with:
          webhook_dev: ${{ secrets.DISCORD_WEBHOOK_DEV }}
          webhook_alerts: ${{ secrets.DISCORD_WEBHOOK_ALERTS }}
          webhook_announcements: ${{ secrets.DISCORD_WEBHOOK_ANNOUNCEMENTS }}
          config_file: 'config.json' # Optional, defaults to config.json
